name: sari_pos
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.9.0
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.6.1
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.1.0
  go_router: ^16.2.4
  logger: ^2.6.1
  mocktail: ^1.0.4
  pubspec_dependency_sorter: ^1.0.5
  riverpod_annotation: ^2.6.1
dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^10.0.0
flutter:
  uses-material-design: true